// Package ignore generates .dockerignore files tuned to detected ecosystems.
package ignore

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/NotHarshhaa/slimify/pkg/config"
	"github.com/NotHarshhaa/slimify/pkg/ecosystem"
)

// Generator creates .dockerignore files.
type Generator struct {
	Config     *config.Config
	Ecosystems *ecosystem.DetectResult
}

// NewGenerator creates a new ignore file generator.
func NewGenerator(cfg *config.Config, eco *ecosystem.DetectResult) *Generator {
	return &Generator{
		Config:     cfg,
		Ecosystems: eco,
	}
}

// Generate produces the contents of a .dockerignore file.
func (g *Generator) Generate() string {
	var b strings.Builder

	b.WriteString("# ==================================================\n")
	b.WriteString("# .dockerignore — generated by slimify\n")
	b.WriteString("# ==================================================\n")
	b.WriteString("#\n")

	if g.Ecosystems != nil && len(g.Ecosystems.Ecosystems) > 0 {
		b.WriteString(fmt.Sprintf("# Detected ecosystems: %s\n", g.Ecosystems.String()))
	}
	b.WriteString("#\n\n")

	// Universal patterns
	b.WriteString("# --- Universal ---\n")
	universalPatterns := []string{
		".git",
		".gitignore",
		".github",
		".vscode",
		".idea",
		".editorconfig",
		"*.md",
		"LICENSE*",
		"CHANGELOG*",
		"docs/",
		"doc/",
		"test/",
		"tests/",
		"spec/",
		"__tests__/",
		"*.test.*",
		"*.spec.*",
		"coverage/",
		".nyc_output/",
		".env",
		".env.*",
		"!.env.production",
		"docker-compose*.yml",
		"docker-compose*.yaml",
		"Makefile",
		"Dockerfile*",
		"!Dockerfile",
		".dockerignore",
		"*.log",
		"tmp/",
		".tmp/",
	}
	writePatterns(&b, universalPatterns, g.Config)
	b.WriteString("\n")

	// Ecosystem-specific patterns
	if g.Ecosystems != nil {
		types := g.Ecosystems.Types()
		// Sort for deterministic output
		sort.Slice(types, func(i, j int) bool {
			return string(types[i]) < string(types[j])
		})

		for _, eco := range types {
			patterns := getEcosystemIgnorePatterns(eco)
			if len(patterns) > 0 {
				b.WriteString(fmt.Sprintf("# --- %s ---\n", string(eco)))
				writePatterns(&b, patterns, g.Config)
				b.WriteString("\n")
			}
		}
	}

	// Config blacklist (always ignore)
	if g.Config != nil && len(g.Config.Ignore.Blacklist) > 0 {
		b.WriteString("# --- Custom blacklist ---\n")
		for _, p := range g.Config.Ignore.Blacklist {
			b.WriteString(p + "\n")
		}
		b.WriteString("\n")
	}

	// Config whitelist (never ignore — add as negation)
	if g.Config != nil && len(g.Config.Ignore.Whitelist) > 0 {
		b.WriteString("# --- Whitelisted (not ignored) ---\n")
		for _, p := range g.Config.Ignore.Whitelist {
			if !strings.HasPrefix(p, "!") {
				b.WriteString("!" + p + "\n")
			} else {
				b.WriteString(p + "\n")
			}
		}
		b.WriteString("\n")
	}

	return b.String()
}

// WriteToFile writes the generated ignore content to a file.
// If the file already exists and preserveCustom is true, custom rules
// are preserved and only generated sections are updated.
func (g *Generator) WriteToFile(path string, preserveCustom bool) error {
	content := g.Generate()

	if preserveCustom {
		existing, err := os.ReadFile(path)
		if err == nil {
			content = mergeWithExisting(string(existing), content)
		}
	}

	return os.WriteFile(path, []byte(content), 0644)
}

// writePatterns writes patterns to the builder, skipping whitelisted ones.
func writePatterns(b *strings.Builder, patterns []string, cfg *config.Config) {
	whitelist := make(map[string]bool)
	if cfg != nil {
		for _, w := range cfg.Ignore.Whitelist {
			whitelist[w] = true
		}
	}

	for _, p := range patterns {
		// Skip whitelisted patterns
		trimmed := strings.TrimSuffix(strings.TrimPrefix(p, "!"), "/")
		if whitelist[trimmed] || whitelist[trimmed+"/"] || whitelist[p] {
			continue
		}
		b.WriteString(p + "\n")
	}
}

// getEcosystemIgnorePatterns returns the ignore patterns for a given ecosystem.
func getEcosystemIgnorePatterns(eco ecosystem.Type) []string {
	switch eco {
	case ecosystem.NodeJS:
		return []string{
			"node_modules/",
			".npm/",
			".yarn/",
			".pnpm-store/",
			"*.map",
			"*.d.ts",
			".eslintrc*",
			".prettierrc*",
			"tsconfig*.json",
			"jest.config*",
			".babelrc",
			"webpack.config*",
			".storybook/",
			"storybook-static/",
			".next/",
			".nuxt/",
		}
	case ecosystem.Go:
		return []string{
			"vendor/",
			"*_test.go",
			"testdata/",
			".golangci.yml",
			".golangci.yaml",
		}
	case ecosystem.Python:
		return []string{
			"__pycache__/",
			"*.pyc",
			"*.pyo",
			".pytest_cache/",
			".mypy_cache/",
			".tox/",
			"*.egg-info/",
			"dist/",
			"build/",
			".venv/",
			"venv/",
			"env/",
		}
	case ecosystem.Rust:
		return []string{
			"target/",
			"*.rs.bk",
		}
	case ecosystem.Java:
		return []string{
			"target/",
			"build/",
			".gradle/",
			"*.class",
			".mvn/",
		}
	case ecosystem.Ruby:
		return []string{
			".bundle/",
			"vendor/bundle/",
			".rubocop*",
			"*.gem",
			"log/",
		}
	default:
		return nil
	}
}

// mergeWithExisting preserves custom rules from an existing .dockerignore
// while replacing the generated sections.
func mergeWithExisting(existing, generated string) string {
	// Extract custom rules (lines not in generated sections)
	var customRules []string
	scanner := bufio.NewScanner(strings.NewReader(existing))
	inGeneratedSection := false

	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)

		// Detect generated section markers
		if strings.Contains(trimmed, "generated by slimify") {
			inGeneratedSection = true
			continue
		}

		// End of generated section at double newline
		if inGeneratedSection && trimmed == "" {
			continue
		}

		if !inGeneratedSection && trimmed != "" && !strings.HasPrefix(trimmed, "#") {
			customRules = append(customRules, line)
		}
	}

	if len(customRules) > 0 {
		var b strings.Builder
		b.WriteString(generated)
		b.WriteString("# --- Custom rules (preserved) ---\n")
		for _, rule := range customRules {
			b.WriteString(rule + "\n")
		}
		return b.String()
	}

	return generated
}

// EstimateSavings estimates how many bytes will be saved by using this ignore file.
// It checks the given file list against the generated patterns.
func (g *Generator) EstimateSavings(files []ecosystem.BloatPattern, totalFiles map[string]int64) int64 {
	patterns := g.Generate()
	var saved int64

	for path, size := range totalFiles {
		if matchesIgnoreFile(path, patterns) {
			saved += size
		}
	}

	return saved
}

// matchesIgnoreFile checks if a file path would be matched by an ignore file.
func matchesIgnoreFile(path string, ignoreContent string) bool {
	scanner := bufio.NewScanner(strings.NewReader(ignoreContent))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "!") {
			continue
		}
		// Simple prefix matching
		pattern := strings.TrimSuffix(line, "/")
		if strings.HasPrefix(path, pattern) || strings.Contains(path, "/"+pattern) {
			return true
		}
	}
	return false
}
