package dockerfile

import (
	"fmt"
	"strings"

	"github.com/NotHarshhaa/slimify/pkg/ecosystem"
)

// RewriteOptions controls how the Dockerfile is rewritten.
type RewriteOptions struct {
	// BaseImage overrides the auto-detected base image.
	BaseImage string
	// MultiStage forces a multi-stage rewrite.
	MultiStage bool
	// Ecosystems detected in the project.
	Ecosystems *ecosystem.DetectResult
}

// Rewrite takes a parsed Dockerfile and produces an optimized version.
func Rewrite(df *Dockerfile, opts RewriteOptions) string {
	var b strings.Builder

	b.WriteString("# ============================================\n")
	b.WriteString("# Dockerfile.slimified — generated by slimify\n")
	b.WriteString("# ============================================\n\n")

	baseImage := df.GetBaseImage()
	optimizedBase := optimizeBaseImage(baseImage, opts)

	if opts.MultiStage && !df.IsMultiStage() {
		writeMultiStageRewrite(&b, df, optimizedBase, opts)
	} else {
		writeSingleStageRewrite(&b, df, optimizedBase, opts)
	}

	return b.String()
}

// writeMultiStageRewrite creates a new multi-stage Dockerfile.
func writeMultiStageRewrite(b *strings.Builder, df *Dockerfile, base string, opts RewriteOptions) {
	buildBase := df.GetBaseImage()
	if opts.BaseImage != "" {
		buildBase = opts.BaseImage
	}

	// Build stage
	b.WriteString("# --- Build stage ---\n")
	b.WriteString(fmt.Sprintf("FROM %s AS builder\n\n", buildBase))
	b.WriteString("WORKDIR /app\n\n")

	// Determine ecosystem-specific build steps
	if opts.Ecosystems != nil {
		if opts.Ecosystems.HasEcosystem(ecosystem.NodeJS) {
			writeNodeBuildStage(b, df)
		} else if opts.Ecosystems.HasEcosystem(ecosystem.Go) {
			writeGoBuildStage(b, df)
		} else if opts.Ecosystems.HasEcosystem(ecosystem.Python) {
			writePythonBuildStage(b, df)
		} else if opts.Ecosystems.HasEcosystem(ecosystem.Rust) {
			writeRustBuildStage(b, df)
		} else if opts.Ecosystems.HasEcosystem(ecosystem.Java) {
			writeJavaBuildStage(b, df)
		} else {
			writeGenericBuildStage(b, df)
		}
	} else {
		writeGenericBuildStage(b, df)
	}

	// Production stage
	b.WriteString("\n# --- Production stage ---\n")
	b.WriteString(fmt.Sprintf("FROM %s AS production\n\n", base))
	b.WriteString("WORKDIR /app\n\n")

	if opts.Ecosystems != nil {
		if opts.Ecosystems.HasEcosystem(ecosystem.NodeJS) {
			writeNodeProdStage(b)
		} else if opts.Ecosystems.HasEcosystem(ecosystem.Go) {
			writeGoProdStage(b)
		} else if opts.Ecosystems.HasEcosystem(ecosystem.Python) {
			writePythonProdStage(b)
		} else if opts.Ecosystems.HasEcosystem(ecosystem.Rust) {
			writeRustProdStage(b)
		} else if opts.Ecosystems.HasEcosystem(ecosystem.Java) {
			writeJavaProdStage(b)
		} else {
			writeGenericProdStage(b)
		}
	} else {
		writeGenericProdStage(b)
	}

	// Find and preserve EXPOSE, ENV, ENTRYPOINT, CMD
	for _, inst := range df.Instructions {
		switch inst.Command {
		case "EXPOSE", "ENV", "ENTRYPOINT", "CMD", "LABEL", "HEALTHCHECK":
			b.WriteString(fmt.Sprintf("%s %s\n", inst.Command, inst.Args))
		}
	}
}

// writeSingleStageRewrite optimizes an existing Dockerfile without multi-stage.
func writeSingleStageRewrite(b *strings.Builder, df *Dockerfile, base string, opts RewriteOptions) {
	// Collect RUN instructions to merge
	var mergedRuns []string
	inRunSequence := false

	for _, inst := range df.Instructions {
		switch inst.Command {
		case "FROM":
			b.WriteString(fmt.Sprintf("FROM %s\n\n", base))
		case "RUN":
			// Merge consecutive RUN instructions
			cmd := optimizeRunInstruction(inst.Args)
			if inRunSequence {
				mergedRuns = append(mergedRuns, cmd)
			} else {
				inRunSequence = true
				mergedRuns = []string{cmd}
			}
		default:
			// Flush any accumulated RUN instructions
			if inRunSequence {
				flushRuns(b, mergedRuns)
				inRunSequence = false
				mergedRuns = nil
			}
			b.WriteString(fmt.Sprintf("%s %s\n", inst.Command, inst.Args))
		}
	}

	// Flush remaining RUNs
	if inRunSequence {
		flushRuns(b, mergedRuns)
	}
}

// flushRuns writes accumulated RUN instructions as a single merged RUN.
func flushRuns(b *strings.Builder, runs []string) {
	if len(runs) == 0 {
		return
	}
	if len(runs) == 1 {
		b.WriteString(fmt.Sprintf("RUN %s\n", runs[0]))
		return
	}
	b.WriteString("RUN ")
	for i, run := range runs {
		if i > 0 {
			b.WriteString(" && \\\n    ")
		}
		b.WriteString(run)
	}
	b.WriteString("\n")
}

// optimizeRunInstruction cleans up a RUN instruction.
func optimizeRunInstruction(args string) string {
	// Add --no-cache to apk
	if strings.Contains(args, "apk add") && !strings.Contains(args, "--no-cache") {
		args = strings.Replace(args, "apk add", "apk add --no-cache", 1)
	}

	// Add cleanup to apt-get
	if strings.Contains(args, "apt-get install") {
		if !strings.Contains(args, "rm -rf /var/lib/apt/lists") {
			args = args + " && rm -rf /var/lib/apt/lists/*"
		}
	}

	return args
}

// optimizeBaseImage suggests an optimized base image.
func optimizeBaseImage(current string, opts RewriteOptions) string {
	if opts.BaseImage != "" {
		return opts.BaseImage
	}

	lower := strings.ToLower(current)

	// Already optimized
	if strings.Contains(lower, "alpine") || strings.Contains(lower, "slim") || strings.Contains(lower, "distroless") {
		return current
	}

	// Suggest alpine variants
	switch {
	case strings.HasPrefix(lower, "node:"):
		parts := strings.SplitN(current, ":", 2)
		version := parts[1]
		// Remove any existing tags
		version = strings.Split(version, "-")[0]
		return fmt.Sprintf("node:%s-alpine", version)
	case strings.HasPrefix(lower, "python:"):
		parts := strings.SplitN(current, ":", 2)
		version := parts[1]
		version = strings.Split(version, "-")[0]
		return fmt.Sprintf("python:%s-slim", version)
	case strings.HasPrefix(lower, "golang:"):
		parts := strings.SplitN(current, ":", 2)
		version := parts[1]
		version = strings.Split(version, "-")[0]
		return fmt.Sprintf("golang:%s-alpine", version)
	case strings.HasPrefix(lower, "ruby:"):
		parts := strings.SplitN(current, ":", 2)
		version := parts[1]
		version = strings.Split(version, "-")[0]
		return fmt.Sprintf("ruby:%s-slim", version)
	case strings.HasPrefix(lower, "openjdk:") || strings.HasPrefix(lower, "eclipse-temurin:"):
		return current + "-alpine"
	default:
		return current
	}
}

// --- Ecosystem-specific build stage templates ---

func writeNodeBuildStage(b *strings.Builder, df *Dockerfile) {
	b.WriteString("# Copy dependency manifests first for better caching\n")
	b.WriteString("COPY package*.json ./\n")

	// Check if yarn is used
	hasYarn := false
	for _, inst := range df.Instructions {
		if strings.Contains(inst.Args, "yarn") {
			hasYarn = true
			break
		}
	}

	if hasYarn {
		b.WriteString("COPY yarn.lock* ./\n")
		b.WriteString("RUN yarn install --frozen-lockfile\n\n")
	} else {
		b.WriteString("RUN npm ci --only=production\n\n")
	}

	b.WriteString("# Copy source and build\n")
	b.WriteString("COPY . .\n")

	// Find build command from original Dockerfile
	for _, inst := range df.Instructions {
		if inst.Command == "RUN" && (strings.Contains(inst.Args, "npm run build") || strings.Contains(inst.Args, "yarn build")) {
			b.WriteString(fmt.Sprintf("RUN %s\n", inst.Args))
			break
		}
	}
}

func writeNodeProdStage(b *strings.Builder) {
	b.WriteString("# Copy only production dependencies and built artifacts\n")
	b.WriteString("COPY --from=builder /app/package*.json ./\n")
	b.WriteString("RUN npm ci --only=production && npm cache clean --force\n\n")
	b.WriteString("COPY --from=builder /app/dist ./dist\n\n")
}

func writeGoBuildStage(b *strings.Builder, df *Dockerfile) {
	b.WriteString("# Copy go module files first for caching\n")
	b.WriteString("COPY go.mod go.sum ./\n")
	b.WriteString("RUN go mod download\n\n")
	b.WriteString("# Copy source and build\n")
	b.WriteString("COPY . .\n")
	b.WriteString("RUN CGO_ENABLED=0 GOOS=linux go build -ldflags='-s -w' -o /app/server .\n")
}

func writeGoProdStage(b *strings.Builder) {
	b.WriteString("# Copy only the compiled binary\n")
	b.WriteString("COPY --from=builder /app/server /app/server\n\n")
}

func writePythonBuildStage(b *strings.Builder, df *Dockerfile) {
	b.WriteString("# Copy requirements first for caching\n")
	b.WriteString("COPY requirements*.txt ./\n")
	b.WriteString("RUN pip install --no-cache-dir --prefix=/install -r requirements.txt\n\n")
	b.WriteString("# Copy source\n")
	b.WriteString("COPY . .\n")
}

func writePythonProdStage(b *strings.Builder) {
	b.WriteString("# Copy installed packages and source\n")
	b.WriteString("COPY --from=builder /install /usr/local\n")
	b.WriteString("COPY --from=builder /app .\n\n")
}

func writeRustBuildStage(b *strings.Builder, df *Dockerfile) {
	b.WriteString("# Copy manifests\n")
	b.WriteString("COPY Cargo.toml Cargo.lock ./\n")
	b.WriteString("RUN mkdir src && echo 'fn main() {}' > src/main.rs\n")
	b.WriteString("RUN cargo build --release\n\n")
	b.WriteString("# Copy real source and rebuild\n")
	b.WriteString("COPY . .\n")
	b.WriteString("RUN touch src/main.rs && cargo build --release\n")
}

func writeRustProdStage(b *strings.Builder) {
	b.WriteString("# Copy only the compiled binary\n")
	b.WriteString("COPY --from=builder /app/target/release/app /usr/local/bin/app\n\n")
}

func writeJavaBuildStage(b *strings.Builder, df *Dockerfile) {
	b.WriteString("# Copy build files\n")
	b.WriteString("COPY pom.xml ./\n")
	b.WriteString("RUN mvn dependency:go-offline\n\n")
	b.WriteString("# Copy source and build\n")
	b.WriteString("COPY . .\n")
	b.WriteString("RUN mvn package -DskipTests\n")
}

func writeJavaProdStage(b *strings.Builder) {
	b.WriteString("# Copy only the built JAR\n")
	b.WriteString("COPY --from=builder /app/target/*.jar /app/app.jar\n\n")
}

func writeGenericBuildStage(b *strings.Builder, df *Dockerfile) {
	b.WriteString("# Copy source\n")
	b.WriteString("COPY . .\n\n")

	// Preserve original RUN instructions
	for _, inst := range df.Instructions {
		if inst.Command == "RUN" {
			b.WriteString(fmt.Sprintf("RUN %s\n", optimizeRunInstruction(inst.Args)))
		}
	}
}

func writeGenericProdStage(b *strings.Builder) {
	b.WriteString("# Copy built artifacts from builder\n")
	b.WriteString("COPY --from=builder /app .\n\n")
}
